# Generated by Django 4.2.1 on 2023-05-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=128),
            preserve_default=False,
        ),
    ]
