# Generated by Django 4.2.1 on 2023-05-27 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
